import {getRandomInteger, getRandomParagraph, getRandomBoolean, getName, getComments} from './mockHelpers';

export const getFilm = () => ({
  title: [
    `The Godfather`,
    `Shawshank Redemption`,
    `Schindler's List`,
    `Raging Bull`,
    `Casablanca`,
    `Citizen Kane`,
    `Gone with the Wind`,
    `The Wizard of Oz`,
    `Flying over the cuckoo's nest`,
    `Lawrence of Arabia`,
    `Obsession`,
    `Psycho`,
    `Godfather 2`,
    `In the port`,
    `Sunset Boulevard`
  ][getRandomInteger(0, 14)],
  titleOriginal: [
    `The Godfather`,
    `Shawshank Redemption`,
    `Schindler's List`,
    `Raging Bull`,
    `Casablanca`,
    `Citizen Kane`,
    `Gone with the Wind`,
    `The Wizard of Oz`,
    `Flying over the cuckoo's nest`,
    `Lawrence of Arabia`,
    `Obsession`,
    `Psycho`,
    `Godfather 2`,
    `In the port`,
    `Sunset Boulevard`
  ][getRandomInteger(0, 14)],
  posterURL: [
    `./images/posters/the-dance-of-life.jpg`,
    `./images/posters/sagebrush-trail.jpg`,
    `./images/posters/santa-claus-conquers-the-martians.jpg`,
    `./images/posters/popeye-meets-sinbad.png`,
    `./images/posters/the-man-with-the-golden-arm.jpg`,
    `./images/posters/the-great-flamarion.jpg`,
  ][getRandomInteger(0, 5)],
  ageRestriction: getRandomInteger(6, 21),
  rating: [
    `G`,
    `PG`,
    `PG-13`,
    `R`,
    `NC-17`,
    `U`,
    `NR`,
  ][getRandomInteger(0, 6)],
  director: getName(),
  writers: Array(getRandomInteger(1, 3)).fill(``).map(getName),
  actors: Array(getRandomInteger(1, 8)).fill(``).map(getName),
  releaseDate: `19${getRandomInteger(10, 99)}`,
  duration: `${getRandomInteger(0, 2)}h ${getRandomInteger(10, 59)}m`,
  country: [
    `USA`,
    `Germany`,
    `Italy`,
    `UK`,
    `Netherlands`,
    `Hong Kong`,
    `Russia`,
  ][getRandomInteger(0, 6)],
  genres: new Set([
    `Horror`,
    `Drama`,
    `Comedy`,
    `Action`,
    `Noir`,
    `Biography`,
    `Crime`,
    `Mystery`,
    `Romance`,
    `Family`,
    `Fantasy`,
  ]),
  description: getRandomParagraph(getRandomInteger(1, 3)),
  commentsCount: getRandomInteger(1, 4),
  activeControls: {
    watchlist: getRandomBoolean(),
    watched: getRandomBoolean(),
    favorite: getRandomBoolean(),
  },
  id: getRandomInteger(1, Number.MAX_SAFE_INTEGER),
});

export const films = Array(getRandomInteger(1, 18)).fill(``).map(getFilm);

export const comments = films.map((film) => getComments(film.id));
